### ISSUE TITLE
[Submission]: 

### ISSUE THREAD

**Issue by CoachSteveMichael** [docker/extensions-submissions#106]
### Docker Hub repository name

kubbybuddy/kubby-buddy-extension
### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by CoachSteveMichael** [comment]
### Docker Hub repository name
kubbybuddy/kubby-buddy-extension

**Comment by benja-M-1** [comment]
@CoachSteveMichael thanks for the submission! Just one tiny detail, can you change the icon that appears in the sidebar when the extension is installed? It is the docker whale at the moment.

**Comment by CoachSteveMichael** [comment]
@benja-M-1 Hi!  Thank you so much for reviewing it.

I updated it in the 1.0.6 version.  Please let me know if there's anything else you need!  We're so stoked to see this in the marketplace.

**Comment by benja-M-1** [comment]
/validate

I restart the validation to have the link to try the new version :)

**Comment by benja-M-1** [comment]
Hi @CoachSteveMichael the icon defined in the label of the image does not work in the marketplace. I can't see [it](https://drive.google.com/file/d/1kvXxK0foZnwQxX3_wGWhfRXiBU--DMrq/view?usp=sharing ) either in a browser.

<img width="991" alt="Screenshot 2023-07-07 at 09 11 28" src="https://github.com/docker/extensions-submissions/assets/212269/4ef33966-1935-473b-8e00-ab6e42f34300">

**Comment by CoachSteveMichael** [comment]
Hi @benja-M-1 Thanks for noticing that!  Sorry, that must be frustrating to have to double check.

We updated the embed link in our Dockerfile.

The newest version 1.0.8 should be okay.

<img width="1728" alt="Screenshot 2023-07-07 at 9 11 13 AM" src="https://github.com/docker/extensions-submissions/assets/108921232/03547ddc-9a00-402a-bae3-2ba50a445cfb">
<img width="1728" alt="Screenshot 2023-07-07 at 9 11 23 AM" src="https://github.com/docker/extensions-submissions/assets/108921232/ee66ea08-ae39-497d-8d54-14c8670a14a9">
