### ISSUE TITLE
[Submission]: Selenium Docker Extension

### ISSUE THREAD

**Issue by ajeetraina** [docker/extensions-submissions#109]
### Docker Hub repository name

ajeetraina/selenium-docker-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by lucbpz** [comment]
Hi @ajeetraina! I installed the extension and the main screen appears blank. I see there's a Selenium container that can be opened on `localhost:4442` but it doesn't show anything either.

Do you want to address this before publishing?

**Comment by gtardif** [comment]
Same for me initially. After I moved to containers screen and came back to the extension, then I can se the UI. It's likely lacking a waiting screen for when the backend containers are still starting ? (This is highly impacting the user experience, as users navigate to the extension just after installing, and the first experience is "it is broken")

**Comment by ajeetraina** [comment]
@lucbpz I noticed that whenever we use Embedded UI, it takes 7-8 seconds for UI to come up.

**Comment by lucbpz** [comment]
@ajeetraina The issue on my side was resolved by increasing the allocated memory to 4GB, in case you want to add this to the description.

About the Embedded UI, it only happens on the first start, when the container is still starting and not available yet. The behavior is the same as if you visit `localhost:4444` in the browser. For now the waiting screen needs to be added manually - you could ping / request the service every X seconds and check when the container is up and running.

**Comment by ajeetraina** [comment]
@lucbpz I have updated the description. Will be performing the validation again.
