### ISSUE TITLE
[Submission]: Kafka Sonar Docker Desktop extension

### ISSUE THREAD

**Issue by stekim4** [docker/extensions-submissions#115]
### Docker Hub repository name

kafkasonar/kafkasonar

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by stekim4** [comment]
### Docker Hub repository name

kafkasonar/kafkasonar

**Comment by lucbpz** [comment]
Hi @stekim4!

We also received your request to be reviewed in the Marketplace. Just wanted to confirm that you want both. I tried creating an account to test the extension, but I'm always receiving an error "Error signing up". Are there any restrictions on username or password?

Let me know if you want us to proceed with publishing it as is and we can do the review process later. Thanks!

**Comment by stekim4** [comment]
Hello @lucbpz!

Yes we are definitely interested in pursuing both the self-publishing route as well as the Docker review route. We understand the Docker review may take a while and that's totally fine.

With regards to your question about restrictions on username - there is a basic input validation for username (at least 3 digits & only letters, digits, and underscores), but this error should trigger a different error - "Provide a valid username".

I pushed a new image to **kafkasonar/kafkasonar** and this update should give us more information about the "Error signing up" issue you're experiencing. 

For example:
![image](https://github.com/docker/extensions-submissions/assets/117881532/47bf6200-6e41-4f44-ba99-bdc2f66954cc)

Would you be able to install the extension again and pass along the extended error message? Also, would you be able to confirm that when the extension is running, there is a container called **timescaledb** running on port 5432? 

Thank you!

**Comment by lucbpz** [comment]
Awesome @stekim4! I had some problem with the `timescaledb` container, that was it 🎉 . I'll revalidate again as you pushed a new image, and publish it in the marketplace. In the following days we'll start your review process 👍
