### ISSUE TITLE
[Submission]: Apache JMeter Docker Extension

### ISSUE THREAD

**Issue by QAInsights** [docker/extensions-submissions#126]
### Docker Hub repository name

qainsights/jmeter-docker-extension:0.0.1

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by benja-M-1** [comment]
Thanks @QAInsights for your extension and your patience with the tool! We are looking into the failures.
