### ISSUE TITLE
[Submission]: 

### ISSUE THREAD

**Issue by Choebryan** [docker/extensions-submissions#129]
### Docker Hub repository name

dockasaurusrx/dockasaurusrx

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by Choebryan** [comment]
Hi,

I ran the docker extension validate command locally on my computer and it
passed all checks. I saw that the error in the github was due to the Docker
Engine not running at the time of the validation. It would be greatly
appreciated if the Docker Desktop is running before the validation check is
ran.

Thank you

**Comment by benja-M-1** [comment]
@Choebryan sorry for the inconvenience, we finally managed to fix the validation! 😮‍💨

**Comment by benja-M-1** [comment]
I will investigate because the command works locally and there are no issue with the validation actually...

**Comment by benja-M-1** [comment]
<img width="1301" alt="Screenshot 2023-11-09 at 12 35 59" src="https://github.com/docker/extensions-submissions/assets/212269/dde10f0a-ce4f-46e2-9c6e-388c30028185">
Adding the label to unblock this submission
