### ISSUE TITLE
[Submission]: PHP Dumper Docker Extension

### ISSUE THREAD

**Issue by markomilivojevic** [docker/extensions-submissions#130]
### Docker Hub repository name

artifision/php-dumper-docker-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by Frezzle** [comment]
Nice work @markomilivojevic! The extension is now available in the marketplace:
<img width="1624" alt="Screenshot 2023-11-08 at 15 09 28" src="https://github.com/docker/extensions-submissions/assets/5685776/89ca4bca-710f-4d9d-8952-99310194a3f1">
