### ISSUE TITLE
[Submission]: qainsights/jmeter-docker-extension:0.0.2

### ISSUE THREAD

**Issue by QAInsights** [docker/extensions-submissions#131]
### Docker Hub repository name

qainsights/jmeter-docker-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by lucadruda** [comment]
There's was a problem with previous submission now being solved. Will close this in favour of #126. Sorry for the inconvenience.
