### ISSUE TITLE
[Submission]: Kubescape 0.1.1

### ISSUE THREAD

**Issue by amirmalka** [docker/extensions-submissions#143]
### Docker Hub repository name

vklokun/docker-desktop-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by ivan-curkovic** [comment]
hi @amirmalka,
If you push a new SemVer version to the Docker Hub, it will be automatically shown to the users.
No need to manually submit the ticket here.

Thanks,
Ivan from Docker
