### ISSUE TITLE
[Submission]: AnalysisG

### ISSUE THREAD

**Issue by woywoy123** [docker/extensions-submissions#144]
### Docker Hub repository name

docker/analysisg
### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by benja-M-1** [comment]
Hi @woywoy123 I couldn't find the image of your project on Docker Hub. Have you pushed it there?
When done, the content of the `Docker Hub repository name` input must be the namespace/repository of the image. For example, if I push an image on my personal namespace on hub for the foo extension like `docker push benjaming/foo-extension:0.0.1`, the value of the input would be `benjaming/foo-extension`.

**Comment by woywoy123** [comment]
Hello Benja, I apologies for the late response, I am still getting familiar with docker. So apologies for the issue. Do I need to create an account for pushing images?

**Comment by benja-M-1** [comment]
Hi @woywoy123 yes you need to create an account on hub.docker.com to be able to push an image there.
