### ISSUE TITLE
[Submission]: Keploy extension for docker desktop

### ISSUE THREAD

**Issue by Yaxhveer** [docker/extensions-submissions#151]
### Docker Hub repository name

yaxhveer/keploy:1.0.0

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by gtardif** [comment]
Hi, I quicky installed the extension, could you do some minor improvement before this can make it to the marketplace:
* Change the docker.svg file copied in the extension image. This is the icon that appears when running the extension (icon in red circle). Please test it in dark/light mode to see how it renders.

<img width="1382" alt="Screenshot 2024-03-26 at 10 36 16" src="https://github.com/docker/extensions-submissions/assets/437958/5d6a6b1d-96bd-49ef-b26b-b906403abf3f">
