### ISSUE TITLE
[Submission]: 

### ISSUE THREAD

**Issue by LLotme** [docker/extensions-submissions#155]
### Docker Hub repository name

@docker/extension-api-client

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by gtardif** [comment]
@LLotme you will need to provide the hub repo name of your extension (without "@") in the description if you want to submit your extension for validation. Don't hesitate to reopen, or create a new issue with your extension repo name.
