### ISSUE TITLE
[Submission]: Docker Labs VSCode Installer

### ISSUE THREAD

**Issue by ColinMcNeil** [docker/extensions-submissions#156]
### Docker Hub repository name

docker/labs-vscode-installer

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by gtardif** [comment]
Hi @ColinMcNeil , Thx for submitting this extension! 
I'm not sure if you really intend to publish this extension to the marketplace: the first thing displayed in the extension main panel is : `Disclaimer: extensions are ready for evaluation, but are not ready to enter the public marketplace.`. 

(Nit: just after this it displays `code command exists`, this probably requires a bit of context or explanation, at the moment it is not clear what the user is supposed to do with this)

**Comment by gtardif** [comment]
I forgot to mention, BTW, the extension is lacking an icon (the label com.docker.desktop.extension must be a public URL that will get displayed in the marketpace) , and the description shows an invalid image

**Comment by ColinMcNeil** [comment]
@gtardif Sorry, I have updated to wording in the page to make sure it is clear that the extensions are for VSCode. The basic idea is that this extension is a GUI wrapper for pulling our VSCode extension bundles and running `code --install-extension`

**Comment by gtardif** [comment]
> There is no way to bundle the icon and screenshots with the image?

The extension image is only downloaded upon install ; only the manifest is to build the marketplace info, so the icon/screenshots must be publicly downloadable for the marketplace (note we download screenshots once while consolidating marketplace info, and save screenshots in our own S3 bucket)

**Comment by ColinMcNeil** [comment]
Sorry for long delay. Logo is added.

**Comment by gtardif** [comment]
Hi, Thx for the update!
Unfortunately, the icon does not show up well in light mode: 
<img width="227" alt="Screenshot 2024-07-29 at 12 26 53" src="https://github.com/user-attachments/assets/1116a1a1-679e-4fe9-b5f6-24713bd35931">
Also, in dark mode it is quite small and almost impossible to read the text in the icon ; maybe the icon should be simplified to include less text and be more readable? 

And the icon displayed in the marketplace needs to be a public URL (as we dont download the full image to show the marketplace info) ; image label `"com.docker.desktop.extension.icon": "./docker.svg"` needs to be a public URL for the svg
You can install your extension and check how the extension displays in the marketplace with the menu "Extensions > Manage"
<img width="1072" alt="Screenshot 2024-07-29 at 12 30 46" src="https://github.com/user-attachments/assets/45a83d1a-25d2-4c52-86ec-ae894f360a40">

**Comment by ColinMcNeil** [comment]
Just pushed a new icon with proper contrast on light & darkmode.
