### ISSUE TITLE
[Submission]: vishalvivekanandan05/dockular-extension:0.0.1

### ISSUE THREAD

**Issue by vishalVivekanandan** [docker/extensions-submissions#157]
### Docker Hub repository name

vishalvivekanandan05/dockular-extension:0.0.1

### Terms of services

- [x] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by vishalVivekanandan** [comment]
Hi @gtardif, hope you're doing well! I've edited the name of the extension as per your suggestions and the validation has passed. Also, I didn’t add the check marks for the build cache because they can’t be pruned the same way compared to containers. It’s implemented this way so they can view the build cache for now. The build cache prune feature is still in beta as per our readme and we hope to get it working soon. Please let me know if you can publish the extension to the marketplace. Thank you!

**Comment by gtardif** [comment]
Thx for the update @vishalVivekanandan, the extension should be in the marketplace soon 🎉

**Comment by vishalVivekanandan** [comment]
Hi @gtardif, it looks like our extension is still not on  Docker Desktop Marketplace as of now. We're not sure why it's still not appearing, could you let us know if there's anything else we need to do on our end? We're trying to add the extension itself (not the image), but we can't find it on Docker Desktop. Thanks.

**Comment by vishalVivekanandan** [comment]
Hi @gtardif, I just checked the marketplace and it looks like it's up now. Thanks!

**Comment by vishalVivekanandan** [comment]
Hi @gtardif, following up regarding the launch of Dockular, I was wondering if you or someone else could manually review our extension so that our extension doesn't appear as unreviewed? If this may be possible, we'd greatly appreciate it thanks!
