### ISSUE TITLE
[Submission]: Dive Into KCNA

### ISSUE THREAD

**Issue by spurin** [docker/extensions-submissions#158]
### Docker Hub repository name

spurin/diveintokcna-lab-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by gtardif** [comment]
Hi @spurin, we have an issue with extension automated validation process, we're looking into it. This error message in the above comments is not related to your extension.

**Comment by spurin** [comment]
Hi @gtardif, @ivan-curkovic

Hope you are both doing well. I would like to remove this extension please, specifically - `spurin/diveintokcna-lab-extension:1.0.1`

It has been superseded by my newer extension that was recently published.

I looked through the extension docs, and I am unsure on what the process is for removing an extension. I noticed in one of the [issues](https://github.com/docker/extensions-submissions/issues/89) that it was automatically flagged when someone removed the repo from docker hub, but, not sure if this was fallout or the preferred approach?

If you can let me know the best way to continue, if there is action required I'll follow your guide, otherwise, please proceed to remove `spurin/diveintokcna-lab-extension:1.0.1` at your convenience.

Thanks

- James
