### ISSUE TITLE
[Submission]: Log Lens

### ISSUE THREAD

**Issue by edwin-abraham-thomas** [docker/extensions-submissions#170]
### Docker Hub repository name

edwinat/loglens

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by edwin-abraham-thomas** [comment]
Hi, can someone take a look at this? 
It looks like the docker desktop's setting is not allowing non-marketplace extensions. I have published a new version (edwinat/loglens:0.1.1-alpha) and the validation succeeded in my local for the new one - ```🎉 The extension \"edwinat/loglens:0.1.1-alpha\" passes the validation checks.\n```

**Comment by gtardif** [comment]
Hello, I'm looking into this, it is indeed an issue with the configuration of Docker Desktop in the automated validation process. Trying to unblock this ASAP.
