### ISSUE TITLE
[Submission]: Daytona Docker Extension

### ISSUE THREAD

**Issue by Tpuljak** [docker/extensions-submissions#174]
### Docker Hub repository name

daytonaio/docker-extension

### Terms of services

- [x] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by gtardif** [comment]
Hi @Tpuljak, I tried to install the extension and when I open it, I see a brief progress bar, and then an empty screen. 
Chrome dev tools show an error happening in the UI

![Image](https://github.com/user-attachments/assets/71ac512a-2687-4604-8ea1-915d970a287b)

**Comment by Tpuljak** [comment]
Ah, I see the issue. Thanks for reporting.

We'll have a fix for that published asap.

**Comment by Tpuljak** [comment]
@gtardif pushed a fix on `daytonaio/docker-extension:0.44.1`. Let me know if you still have any issues. Thanks!

**Comment by Tpuljak** [comment]
@gtardif thanks for the approval!

Just to confirm, we don't need to create a submission request for every version of the extension? A new version is automatically published once we push to Hub.

**Comment by gtardif** [comment]
> Just to confirm, we don't need to create a submission request for every version of the extension? A new version is automatically published once we push to Hub.

No, once the extension is in the marketplace, you don't need to re-submit the extension, you simply need to push new tags following semver semantics. 

Your extension should be shortly added in the marketplace.
