### ISSUE TITLE
[Submission]: KWasm

### ISSUE THREAD

**Issue by 0xE282B0** [docker/extensions-submissions#49]
### Docker Hub repository name

0xe282b0/kwasm-docker-desktop

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by benja-M-1** [comment]
Hi @0xE282B0 thank you for your submission!

I installed the extension to have a look :) I have some feedback for you, where is the best place to send it to you?

**Comment by 0xE282B0** [comment]
I'm afraid it is not very useful without some background information 😅

Twitter: 0xE282B0
Mastodon: @0xe282b0@hachyderm.io
Linkedin: https://www.linkedin.com/in/sven-pfennig/
Or the email from DockerHub 😊

**Comment by benja-M-1** [comment]
I was more thinking about an issue tracker so I found the GitHub repo, should I open an issue there? Or you prefer an email? :)

**Comment by 0xE282B0** [comment]
Yes, issues are fine!

**Comment by benja-M-1** [comment]
@0xE282B0 We are fine-tuning the publishing process, so it took longer than it should have. But things are all good now :) Restart DD to avoid waiting for the next cache refresh of the app, and you should see the extension in the marketplace.

**Comment by 0xE282B0** [comment]
Do I need to resubmit when I updated the extension?

**Comment by benja-M-1** [comment]
@0xE282B0 no you simply have to create a new semver tag. Our system watch new semver tags every hours on the hour.
