### ISSUE TITLE
[Submission]: Neo4j Docker Extension

### ISSUE THREAD

**Issue by collabnix** [docker/extensions-submissions#59]
### Docker Hub repository name

ajeetraina/neo4j-docker-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by benja-M-1** [comment]
Hi @collabnix can you change the publisher value set in the labels? It is set as Docker Inc.

<img width="715" alt="Screenshot 2023-03-10 at 14 41 51" src="https://user-images.githubusercontent.com/212269/224330983-d0e854e7-d6a6-4e1c-b162-28227e58bcdd.png">

**Comment by collabnix** [comment]
@benja-M-1 I have fixed it under https://open.docker.com/extensions/marketplace?extensionId=ajeetraina/neo4j-docker-extension&tag=0.0.2

**Comment by collabnix** [comment]
I have fixed the icon under 1.0.0 release. Will run the next level of validation again.

**Comment by benja-M-1** [comment]
/validate

The extension name contained the version, and it should not. Otherwise, it does not validate the highest semver tag of the image. I fixed that. We must wait for the validation to run again.
