### ISSUE TITLE
[Submission]: BlocklyAutomation

### ISSUE THREAD

**Issue by ignatandrei** [docker/extensions-submissions#62]
### Docker Hub repository name

ignatandrei/blockly-automation

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by ignatandrei** [comment]
The image is https://hub.docker.com/r/ignatandrei/blockly-automation . It is like newman image, but with blocks

**Comment by benja-M-1** [comment]
I changed the repository name in the description so the validation works

**Comment by benja-M-1** [comment]
@ignatandrei now there is a real validation issue to fix :)

**Comment by ignatandrei** [comment]
Hello @benja-M-1  - could you please tell me where I can fix ?  Or should I publish the extension again ?

**Comment by benja-M-1** [comment]
Hi @ignatandrei you have to add the `com.docker.extension.categories` in the Dockerfile of the extension, and create a new tag for the image, push it and comment this issue with `/ validate` :)

**Comment by ignatandrei** [comment]
Hello @benja-M-1 

I tried to do so, but I have an error :
ERROR: failed to solve: dockerfile parse error on line 13: unknown instruction: com.docker.extension.categories="development,testing-tools,utility-tools"


You can reproduce this error by going to https://github.com/ignatandrei/BlocklyAutomation , download, goto src\DeployersToPackage\DockerExtension and execute

docker buildx build --push --platform=linux/amd64,linux/arm64 --tag=ignatandrei/blockly-automation:0.0.6 . 

( or maybe execute deploy.bat from the folder)

Could you please help  ? If it helps, I have on windows

Docker Desktop 4.17.0 (99724) is currently the newest version available.

**Comment by benja-M-1** [comment]
@ignatandrei you need a `\` at the end of this line https://github.com/ignatandrei/BlocklyAutomation/blob/main/src/DeployersToPackage/DockerExtension/Dockerfile#L12

**Comment by ignatandrei** [comment]
Thanks. @benja-M-1
