### ISSUE TITLE
[Submission]: QuestDB Docker Extension

### ISSUE THREAD

**Issue by collabnix** [docker/extensions-submissions#64]
### Docker Hub repository name

ajeetraina/questdb-docker-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by benja-M-1** [comment]
FYI, I changed the image name submitted to remove the version so that we are sure the validation uses the highest semver tag available. I am waiting for its validation to be finished before adding the publish/ready label
