### ISSUE TITLE
[Submission]: Memgraph Docker Extension

### ISSUE THREAD

**Issue by collabnix** [docker/extensions-submissions#67]
### Docker Hub repository name

ajeetraina/memgraph-docker-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by collabnix** [comment]
I shall be pushing the new tag version shortly.

**Comment by benja-M-1** [comment]
I removed the version from the issue description so that the last version available is validated here. Waiting for the result before labelling this issue as `publish/ready`

**Comment by collabnix** [comment]
Look like it picked up the old build as I don't see latest 1.0.1 version. @benja-M-1

**Comment by benja-M-1** [comment]
@collabnix the greatest tag available is 2.6.5, see https://hub.docker.com/r/ajeetraina/memgraph-docker-extension/tags. The process will take this one and not 1.0.1. You should either remove the 2.6.5 tag from hub or tag a new version greater than that. 🙂

**Comment by collabnix** [comment]
@benja-M-1 I have removed 2.6.5. Let me run /validate again.

**Comment by collabnix** [comment]
@benja-M-1 My bad...I should have pushed it to the latest rather than 1.0.1.
Will go ahead and fix it

**Comment by collabnix** [comment]
Wow! It picked up the 1.0.1 version. Now it looks good.
