### ISSUE TITLE
[Submission]: julianb90/tachometer docker extension

### ISSUE THREAD

**Issue by Julian-B90** [docker/extensions-submissions#73]
### Docker Hub repository name

julianb90/tachometer

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by Julian-B90** [comment]
Hey @benja-M-1 yes, i can do it tomorrow :-)

**Comment by Julian-B90** [comment]
@benja-M-1 i have update my icon :-)

**Comment by benja-M-1** [comment]
Thanks @Julian-B90 👍
