### ISSUE TITLE
[Submission]: MindsDB Docker Extension

### ISSUE THREAD

**Issue by collabnix** [docker/extensions-submissions#74]
### Docker Hub repository name

ajeetraina/mindsdb-docker-extension:1.0.0

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by gtardif** [comment]
@ajeetraina Taking a quick look out of curiosity and installing the extension, it installed correctly but when opening it I only saw a blank screen. Eventually, it turns out containers are really slow to start (like several minutes) ; is there a way to have some spinner or way to inform the user things are not broken?

**Comment by collabnix** [comment]
Yes. I was thinking of similar kind of implementation few days back. I am not sure how complex it will be implement the spinner but can check with the team internally.

**Comment by gtardif** [comment]
The image started by the compose app is not multi-arch ; this might be a reason for things being so slow (as it transparently runs on my M1 machine, but emulated with Rosetta). 
We have something in our backlog to also check images mentioned in the compose file and verify they are multi-arch ; for now, could you ensure that all are multi-arch (not sure it will solve the startup time issue, but it can't hurt)

**Comment by collabnix** [comment]
@gtardif You're right. It might be the reason as MindsDB doesn't official ship Arm-based images. I tried using ```make push-extension``` and tried pushing both amd64 and arm-based images but I do understand that it might be slow due to emulated version.

**Comment by collabnix** [comment]
@benja-M-1 We might need to put this on-hold for sometime. I have raised a feature request with MindsDB for shipping Arm-based Docker image to the Docker Hub. Once they push it, I should be able to build it for both architecture.

**Comment by benja-M-1** [comment]
Alright, do you mind if we close the issue for now and reopen it once you go an answer? It makes our work easier when we screen for updates on issues.

**Comment by collabnix** [comment]
Sure. We can go ahead and close this thread.
