### ISSUE TITLE
[Submission]: μ Registry Explorer

### ISSUE THREAD

**Issue by AkiSakurai** [docker/extensions-submissions#77]
### Docker Hub repository name

akisakurai/registry-explorer-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by benja-M-1** [comment]
Hi @AkiSakurai, I see that the extension is a fork of @nico1510's https://github.com/nico1510/registry-explorer-extension. Don't you want to raise a PR on this repo rather than submit it as an extension? I am sure he would be keen on merging this  :)
