### ISSUE TITLE
[Submission]: gopaddle lite extension for docker users

### ISSUE THREAD

**Issue by gopaddle-io** [docker/extensions-submissions#81]
### Docker Hub repository name

gopaddle/gopaddle-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by lucbpz** [comment]
⚠️  Don't publish this one until we have confirmation on their side.

**Comment by benja-M-1** [comment]
I have been given the go to proceed.
