### ISSUE TITLE
[Submission]: remoteit/docker-extension

### ISSUE THREAD

**Issue by robomon1** [docker/extensions-submissions#82]
### Docker Hub repository name

remoteit/docker-extension

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by robomon1** [comment]
@docker/extensions

**Comment by benja-M-1** [comment]
/validate

Hi @robomon1 thanks for submitting your extension :) I allowed myself to edit your submission, the extension repository name should not include the tag. I trigger a new validation here to make sure it does take the right tag automatically.
