### ISSUE TITLE
[Submission]: Topmast

### ISSUE THREAD

**Issue by Chris-isCoding** [docker/extensions-submissions#83]
### Docker Hub repository name

chrisiscoding/topmast

### Terms of services

- [X] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by Chris-isCoding** [comment]
@benja-M-1 
Hello Benjamin, sorry to bother. I was wondering if it would be possible to change the extension address to `topmast/topmast:0.1.2-alpha` I haven't found a way to do it on my end.

The extension has been mistakenly published under an incorrect repository name, and I am uncertain about the appropriate steps to update the address on the published version. I would be grateful for any assistance or pointers you can provide to help me address this issue.

For your reference, here is the link to the Docker Hub repository where the extension is currently hosted: https://hub.docker.com/r/topmast/topmast

Thank you very much for your understanding and support.

**Comment by benja-M-1** [comment]
Hi @Chris-isCoding you can submit the new one. Once the validation pass we will manually update the list on the marketplace. 

The drawback though is that users that already have the extension installed won't be migrated to the new one. What you can do is push a new version on the wrong repo telling the users to uninstall it and install the new one.

**Comment by benja-M-1** [comment]
Hi @Chris-isCoding do you want me to remove this extension from the marketplace and add the other one?

**Comment by Chris-isCoding** [comment]
Hi @benja-M-1 

Yes, please remove this extension from the marketplace and replace it with the other one that has the correct hub docker references. 
I appreciate your help in making this update. 

Thank you

**Comment by benja-M-1** [comment]
Yes we will do

**Comment by benja-M-1** [comment]
@Chris-isCoding we removed it. You can restart your Docker Desktop and it should disappear.
