### ISSUE TITLE
[Submission]: scoritz/runblade-extension

### ISSUE THREAD

**Issue by scoritz** [docker/extensions-submissions#89]
### Docker Hub repository name

scoritz/runblade-extension

### Terms of services

- [x] I accept the [term of services](https://www.docker.com/legal/extensions_marketplace_developer_agreement/)

**Comment by scoritz** [comment]
@benja-M-1 the workflow reports that I've not checked the terms of service?

**Comment by benja-M-1** [comment]
Hi @scoritz, indeed there is an issue. I don't know what is happening yet, locally I manage to have the right result... I'll debug it. In the meantime, I will add the label manually

**Comment by benja-M-1** [comment]
Arf, unfortunately, it didn't work as I expected... Sorry for that @scoritz I'll try to have it solved by today.

**Comment by scoritz** [comment]
@benja-M-1 no worries, much appreciated! 👍

**Comment by scoritz** [comment]
@benja-M-1 any luck, anything I can do to help? let me know

**Comment by benja-M-1** [comment]
@scoritz I tested the extension! That's great! I love it :) Thanks! 
It will be publish in the next hour 👍

**Comment by scoritz** [comment]
@benja-M-1 Thanks so much, appreciate the feedback

**Comment by gtardif** [comment]
Hi @scoritz, it seems the hub image `scoritz/runblade-extension` has been removed from Docker Hub. 
The extension cannot be installed anymore and we cannot re-index it. 

Unfortunately I'll have to remove the extension from the Docker Extension marketplace. Let us know if you fix this and when the image is available again if you want to put your extension back in the marketplace.
